### PR TITLE
Dev kohulan

### PR DESCRIPTION
**Pull request by Kohulan**
Code refactoring, READ Me updated and checked for tSNE bugs

### CODE REVIEW

**Comment by JonasSchaub** [comment]
Could you maybe discard the changes done to the workflow notebook? Because they actually don't have any meaning but GitHub is unable to display them.

**Review by OBrink — COMMENTED** [review]
The refactoring seems fine to me.

####Discussion point:
* What is the basic usage in the README good for?

**Comment by JonasSchaub** [comment]
To show the basic usage of CIDER as a library?

**Comment by Kohulan** [comment]
> The refactoring seems fine to me.
> 
> #### Discussion point:
> * What is the basic usage in the README good for?

We discussed this in yesterday's meeting. We just want to show a user how they can start with CIDER, for more details they can of course refer to the workflow.

**Comment by Kohulan** [comment]
> Could you maybe discard the changes done to the workflow notebook? Because they actually don't have any meaning but GitHub is unable to display them.

No code changes or additions, it is a re-rendering of the whole notebook

**Comment by OBrink** [comment]
I know that we discussed it, but all the example shows is how to read files from a given directory (and it does not say that "data" is a directory)

```
from CIDER import ChemicalDatasetComparator
cider = ChemicalDatasetComparator()

testdict = cider.import_as_data_dict('data')

testdict
```

**Comment by JonasSchaub** [comment]
> No code changes or additions, it is a re-rendering of the whole notebook

If I see it correctly, no code has been re-rendered. Only logs and outputs like paths specific for the local machine have been altered. Is this right?

**Comment by Kohulan** [comment]
> > No code changes or additions, it is a re-rendering of the whole notebook
> 
> If I see it correctly, no code has been re-rendered. Only logs and outputs like paths specific for the local machine have been altered. Is this right?



> I know that we discussed it, but all the example shows is how to read files from a given directory (and it does not say that "data" is a directory)
> 
> ```
> from CIDER import ChemicalDatasetComparator
> cider = ChemicalDatasetComparator()
> 
> testdict = cider.import_as_data_dict('data')
> 
> testdict
> ```
> 
> All I mean is that this example is not actually going to help anyone using CIDER

Ok. I have updated the basic usage in the READ Me. Please check

**Comment by Kohulan** [comment]
> > No code changes or additions, it is a re-rendering of the whole notebook
> 
> If I see it correctly, no code has been re-rendered. Only logs and outputs like paths specific to the local machine have been altered. Is this right?

Yes. There won't be any conflicts

**Comment by JonasSchaub** [comment]
> Yes. There won't be any conflicts

Well, that's what I mean with "these changes have no meaning"...

**Comment by OBrink** [comment]
I just want it to be a bit more obvious that 'data' specifies a directory. How about now?

**Review by OBrink — APPROVED** [review]

**Comment by Kohulan** [comment]
> I just want it to be a bit more obvious that 'data' specifies a directory. How about now?

Looks good thanks 😄

**Comment by OBrink** [comment]
But if the whole notebook is now rendered without the commented t-sne-plot cell, then there *is* a meaningful change

**Comment by JonasSchaub** [comment]
The tsne cell has not been executed if I see this correctly.

**Comment by OBrink** [comment]
Then I agree that it should be executed or the changes in the notebook should be discarded

**Comment by OBrink** [comment]
I see the t-sne plot now. From my side, it can be merged

**Comment by JonasSchaub** [comment]
> I see the t-sne plot now. From my side, it can be merged

Me, too. I also give my approval.

**Pull request merged**
