### PR TITLE
fix: use chemplot with user defined fingerprints  @Kohulan

### PR DESCRIPTION
**Pull request by Kohulan**
Fixes issue #55

### CODE REVIEW

**Comment by JonasSchaub** [comment]
@Kohulan I went to your fork https://github.com/Kohulan/ChemPlot.git to look at your changes in ChemPlot but I can't really make them out because you apparently ran linter over the code, so seemingly a lot has been changed. Can you somehow point me to them?

**Comment by Kohulan** [comment]
> @Kohulan I went to your fork https://github.com/Kohulan/ChemPlot.git to look at your changes in ChemPlot but I can't really make them out because you apparently ran linter over the code, so seemingly a lot has been changed. Can you somehow point me to them?

- https://github.com/Kohulan/ChemPlot/blob/main/chemplot/chemplot.py
Line : 91,92
Line: 213, 214

Similar could be seen in     "@classmethod def from_inchi"

**Comment by OBrink** [comment]
One general remark: I don't think that the ChemPlot developers will ever accept this PR if there are so many changes done by the linter. It's not really reviewable without a considerable amount of work

**Comment by Kohulan** [comment]
> One general remark: I don't think that the ChemPlot developers will ever accept this PR if there are so many changes done by the linter. It's not really reviewable without a considerable amount of work

We could rollback before linter modifications. That is easy.

**Comment by JonasSchaub** [comment]
> We could rollback before linter modifications. That is easy.

Would be much easier to see the actual changes then.
The new parameters have also not been added to the doc strings, if I see that correctly.

@hannbus the last commit https://github.com/hannbus/ChemIcal-DatasEt-comparatoR/pull/57/commits/417d94d938b217f85b15083824116ddddb9cb6ed now actually changed the usage in CIDER, could you review it? Are the changes also accessible in the workflow notebook this way?

**Comment by Kohulan** [comment]
> > One general remark: I don't think that the ChemPlot developers will ever accept this PR if there are so many changes done by the linter. It's not really reviewable without a considerable amount of work
> 
> We could roll back before linter modifications. That is easy.

This is done now: https://github.com/mcsorkun/ChemPlot/pull/21

@Jonas : The workflow notebook does work without any issues.

**Review by JonasSchaub — APPROVED** [review]
Looks good to me, @hannbus  what do you say?

**Comment by JonasSchaub** [comment]
Great! 

Question, we now still have to decide on a smaller default fingerprint size for the CIDER methods (see here https://github.com/hannbus/ChemIcal-DatasEt-comparatoR/issues/55). Should we do this as part of this pull request or somewhere else?

**Comment by Kohulan** [comment]
> Great!
> 
> Question, we now still have to decide on a smaller default fingerprint size for the CIDER methods (see here #55). Should we do this as part of this pull request or somewhere else?

Let's do this here itself.

**Comment by JonasSchaub** [comment]
>>Great!
>>Question, we now still have to decide on a smaller default fingerprint size for the CIDER methods (see here https://github.com/hannbus/ChemIcal-DatasEt-comparatoR/issues/55). Should we do this as part of this pull request or somewhere else?
>
> Let's do this here itself.

@Kohulan, in the issue regarding the FP size, you did a comparison of how the chemical space map of COCONUT and ChEBI changes when the FP size is decreased. There, we were not able to see any changes, of course, because the fp size setting wasn't working. Is it easy for you to do these analyses again now that the setting is working? Or does everybody think that we could just agree on 512 as a reasonable *default* fp size?

**Comment by Kohulan** [comment]
> > > Great!
> > > Question, we now still have to decide on a smaller default fingerprint size for the CIDER methods (see here #55). Should we do this as part of this pull request or somewhere else?
> > 
> > 
> > Let's do this here itself.
> 
> @Kohulan, in the issue regarding the FP size, you did a comparison of how the chemical space map of COCONUT and ChEBI changes when the FP size is decreased. There, we were not able to see any changes, of course, because the fp size setting wasn't working. Is it easy for you to do these analyses again now that the setting is working? Or does everybody think that we could just agree on 512 as a reasonable _default_ fp size?

I would still suggest keeping 512 or less as _default_ fp size. Looking at the plots below I don't think keeping a higher default fp size does make any true value.

256 bits (time elapsed: 7m:10sec)
image


512 bits (time elapsed: 8m:37sec)
image

2048 bits (time elapsed: 16m:15sec)
image

**Comment by JonasSchaub** [comment]
Well, in the end, this is mostly "voodoo magic" anyway. 
But I still wouldn't want to go lower than 512 (out of "a feeling").
But it is also just a default value...

About the failing test: I guess you have to adjust the matplotlib version?

**Comment by Kohulan** [comment]
> Well, in the end, this is mostly "voodoo magic" anyway. But I still wouldn't want to go lower than 512 (out of "a feeling"). But it is also just a default value...
> 
> About the failing test: I guess you have to adjust the matplotlib version?

Fixed!. Let's merge this request.

**Review by JonasSchaub — APPROVED** [review]

**Pull request merged**
