### PR TITLE
fix: Add time to PDF report #65

### PR DESCRIPTION
**Pull request by Kohulan**

### CODE REVIEW

**Comment by JonasSchaub** [comment]
Did you really change sth in the workflow notebook or did you just run it again and the outputs appear as changes?

**Comment by Kohulan** [comment]
> Did you really change sth in the workflow notebook or did you just run it again and the outputs appear as changes?

I ran the whole notebook again to generate the PDF at the end. Nothing was modified there.

**Comment by JonasSchaub** [comment]
Could you then maybe discard your changes there?

**Comment by Kohulan** [comment]
> Could you then maybe discard your changes there?

Why do you want to discard the changes? Does it really matter since nothing has changed?

**Comment by JonasSchaub** [comment]
That's the point, it looks like something (a lot) has changed, when it actually has not. 
It's a recurrent problem I have with Jupyter Notebooks in Git...

**Comment by Kohulan** [comment]
> That's the point, it looks like something (a lot) has changed, when it actually has not. It's a recurrent problem I have with Jupyter Notebooks in Git...

Done now

**Review by JonasSchaub — APPROVED** [review]

**Pull request merged**
